### ISSUE TITLE
[Feature]: Config via a vuetify.config.[js|ts] file

### ISSUE THREAD

**Issue by tidan-16** [invictus-codes/nuxt-vuetify#18]
### Describe the solution you'd like

I would like to be able to add a vuetify.config.js file at the root directory (./vuetify.config.js)

### Additional context

Being able to add the config at the root (vuetify.config.js) would make the nuxt.config.js file cleaner and smaller. Since we all know that the config for vuetify can be almost 50+ lines, it would be nice to seperate it. I know that nuxt i18n allow that and im pretty sure that would be a good approach for this module too. 

Here is the doc for the vue i18n module for that feature:
[https://v8.i18n.nuxtjs.org/options/vue-i18n](https://v8.i18n.nuxtjs.org/options/vue-i18n)

What do you guys think about this idea?

**Comment by tidan-16** [comment]
Closing as im using another library for nuxt and vuetify

**Comment by jvolker** [comment]
> Closing as im using another library for nuxt and vuetify

Do you mind sharing which one?
