### ISSUE TITLE
[Feature]: globals

### ISSUE THREAD

**Issue by proggreg** [invictus-codes/nuxt-vuetify#23]
### Describe the solution you'd like

globals config

### Additional context

not sure if this is possible at the moment but I would like to configure components globally as stated here https://vuetifyjs.com/en/features/global-configuration/

Thanks :)

**Comment by francois2metz** [comment]
Hi. This is already possible using the `vuetifyOptions` option.

**Comment by proggreg** [comment]
Thank you, you are right I was trying to use globals instead of defaults
