### ISSUE TITLE
[Bug]: Unsupported URL Type "link:": link:.

### ISSUE THREAD

**Issue by blowstack** [invictus-codes/nuxt-vuetify#3]
### Contact Details

piotrgolon@gmail.com

### What happened?

Tried installing in a new project   "nuxt": "^3.4.1" with npm.
`npm install --save-dev @invictus.codes/nuxt-vuetify`

And get the following errors:
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:.

### Version

1.0.2 (Default)

**Comment by polus-arcticus** [comment]
tried with yarn, seemed to work

**Comment by Jozaguts** [comment]
Yarn and my currently version of node it was my problem 
>  @invictus.codes/nuxt-vuetify@0.2.18: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.14.2"

**Comment by deepblue1004** [comment]
any solution for npm?

**Comment by jvhellemondt** [comment]
I believe this is caused because the package is used in de playground. I'll try moving it to dev dependencies, that might work. ETA end of this week

**Comment by sam-kleiner** [comment]
Looks like you can change link to file? https://stackoverflow.com/questions/74679689/unsupported-url-type-link-while-using-npm

https://github.com/invictus-codes/nuxt-vuetify/blob/main/package.json#L55

**Comment by i-vanov** [comment]
BITTE WIR BRAUCHEN DAS FÜR DIE NÄCHSTE WOCHE! DANKE SCHÖN!

**Comment by jvhellemondt** [comment]
Fixed with 0.2.19, can you confirm?

**Comment by rdallet** [comment]
npm seems to work now
