### ISSUE TITLE
[Bug]: Cannot install via npm

### ISSUE THREAD

**Issue by QozbroQqn** [invictus-codes/nuxt-vuetify#5]
### What happened?

Error on npm install

### Version

nuxt-vuetify: 0.2.18
npm: 9.6.3
node: 18.15.0

### What browsers are you seeing the problem on?

terminal

### Relevant log output

```shell
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:.
```

**Comment by jvhellemondt** [comment]
Fixed with 0.2.19, can you confirm?

**Comment by QozbroQqn** [comment]
Yes it installs.  Sorry for the duplication.

**Comment by jvhellemondt** [comment]
> Yes it installs.  Sorry for the duplication.

No worries. Enjoy and let me know if you have any requests
